baseURL = "http://example.org/"
languageCode = "en-us"
title = "Gaia's Genie"
theme = "ananke"
[params]
  background_color_class = "bg-dark-green"
  description = "Exploring sustainability"
  googleAnalytics = "G-YYRP978D3Q"