baseURL = "https://gaiasgenie.com/"
languageCode = "en-us"
title = "Gaia's Genie"
theme = "ananke"
googleAnalytics = "G-YYRP978D3Q"
[params]
  background_color_class = "bg-dark-green"
  description = "Exploring sustainability"